Hw1
fitzplsr/go_homework pull request #1
Opened 2023-09-18 16:16 UTC by fitzplsr

ДЗ-1 Халиков Руслан
telegram: @fitzplsr

2023-09-19 13:54 UTC, k-t-l-h requested changes

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/main.go
> +func main() {
Замечательный main! Очень чисто выглядит

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/flagsparser/flagsparser.go
> +	fmt.Println(usageSchema)
Лишнее - в пакете flag уже есть такая функция и у нее больше функционал. Не надо придумывать свое в этом случае

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/uniq/uniq.go
> +			if options.F > (uint)(len(fields)-1) {
Много преобразований, проще сделать переменную int и один раз ее проверить

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/uniq/uniq.go
> +		isMatch := currentLine == prevCutLine
Можно сделать как с record, сделать две функции и потом в зависимости от флага считать одним способом или другим. А так если флаг i включен, то ты дважды сравниваешь строки

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/uniq/uniq.go
> +			countOfRepeated = 1
Или можно сделать  countOfRepeated = 0 и убрать continue

2023-09-19 13:54 UTC, k-t-l-h commented on hw1.1/uniq/uniq_test.go
> +var tests = []struct {
Добавь тесты на кириллицу и посмотри, правильно ли твоя функция работает, если есть флаг s

2023-09-19 19:34 UTC, fitzplsr commented
-Заменил Usage на flag.Usage в пакете flagsparse
-Заменил uint на int в структуре Options и добавил валидацию на измененные поля
-Добавил выбор функции сравнения для исключения лишнего сравнения при наличии флага "i"
-Добавил тесты на кириллице и исправил ошибки при работе с кириллицей

2023-09-20 13:09 UTC, k-t-l-h commented on hw1.1/uniq/uniq.go
> +		compare := equalStrings
Это именно то, что я хотела от тебя, но теперь давай вынесем это из цикла, чтобы не переопределять ее каждый раз

2023-09-20 15:17 UTC, fitzplsr commented
Вынес compare из цикла

2023-09-24 13:03 UTC, k-t-l-h commented on hw1.2/calc/compute.go
> +	return fmt.Sprintf("Error computing expression: %s", e.message)
в go принято ошибки писать с маленькой буквы

2023-09-24 13:04 UTC, k-t-l-h commented on hw1.2/calc/compute.go
> +	if taken == '~' {
Давай попробуем чуть упростить эту функцию :)

2023-09-24 13:05 UTC, k-t-l-h commented on hw1.2/calc/compute.go
> +	switch taken {
что будет, если не придет ни один из этих символов?

2023-09-24 13:07 UTC, k-t-l-h commented on hw1.2/calc/polish.go
> +func getPriority(operation byte) (priority int) {
Приоритеты никогда не меняются - может быть использовать хеш-мапу для быстрого поиска?

2023-09-24 13:08 UTC, k-t-l-h commented on hw1.2/calc/polish.go
> +	if priority == 0 {
Лучше не делать лишние if-else и не использовать именованные переменные, тогда можно избежать ненужного бранчевания

2023-09-27 14:43 UTC, k-t-l-h approved these changes

2023-10-02 10:15 UTC, K1ola requested changes
решение с `compare = strings.EqualFold` уже встречалось в другой дзшке, нужно порефакторить

2023-10-02 10:15 UTC, K1ola commented on hw1.1/iostrings/iostrings.go
> +				log.Fatal("Can't close file")
не следует фаталить без особой надобности. Просто лог ошибки и return

2023-10-02 10:15 UTC, K1ola commented on hw1.1/iostrings/iostrings.go
> +			err = errors.New("can't open file")
не нужно перезаписывать ошибку от os.Open с полезной инфой на свое сообщение. Или оборачивать ошибку или просто возвращать как есть

2023-10-02 10:15 UTC, K1ola commented on hw1.1/iostrings/iostrings.go
> +				log.Fatal("Can't close file")
аналогичное замечание выше

2023-10-02 10:15 UTC, K1ola commented on hw1.1/iostrings/iostrings.go
> +			err = fmt.Errorf("Can't append or create file: %s\n", outputFile)
аналогичное замечание выше. В ошибке от os.OpenFile есть полезная информация, ее не нужно терять

2023-10-02 10:15 UTC, K1ola commented on hw1.1/iostrings/iostrings.go
> +			log.Fatal("Error flushing buffer")
аналогичное замечание выше

2023-10-02 10:15 UTC, K1ola commented on hw1.1/main.go
> +		log.Fatal(err.Error())
тут и далее убрать все log.Fatal, просто логировать ошибку и return

2023-10-02 10:15 UTC, K1ola commented on hw1.1/uniq/uniq.go
> +	record()
для чего нужно заводить для record внутреннюю функцию?

2023-10-02 10:15 UTC, K1ola commented on hw1.1/uniq/uniq_test.go
> +			if !equal(res, tt.out) {
можно воспользоваться assert.Equal(t, tt.out, result)

2023-10-02 10:15 UTC, K1ola commented on hw1.2/calc/compute.go
> +			item, _ := stack.Pop()
если везде опускается 2е значение от stack.Pop(), может и не следует ее возвращаться из функции?

2023-10-02 15:17 UTC, fitzplsr commented on hw1.1/uniq/uniq.go
> +	record()
чтобы корректно записывать последнюю строку

2023-10-02 15:24 UTC, fitzplsr commented
Убрал подмену ошибок
Убрал fatal
Убрал компаратор
Использовал assert.Equal
Убрал 2е возвращаемое значение из Stack.Pop

2024-02-15 21:55 UTC, merged